version: '3'
services:
  ubuntu:
    image: pycontribs/ubuntu:latest
    container_name: ubuntu
    command: sleep infinity
    
  centos7:
    image: pycontribs/centos:7
    container_name: centos7
    command: sleep infinity
    
  fedora:
    image: pycontribs/fedora:latest
    container_name: fedora
    command: sleep infinity