services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - haproxy

  haproxy:
    image: haproxy:alpine
    container_name: haproxy-lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - backend
    depends_on:
      - web
