---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib (rescue)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"
            
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"
          - "/tmp/clickhouse-client-{{ clickhouse_version }}.rpm"
          - "/tmp/clickhouse-server-{{ clickhouse_version }}.rpm"
        disable_gpg_check: true
      notify: Start clickhouse service

    - name: Flush handlers
      meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

# ----------------------------------------
# VECTOR
# ----------------------------------------
- name: Install Vector
  hosts: vector
  vars_files:
    - group_vars/vector/vars.yml
  handlers:
    - name: Restart Vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
      ignore_errors: true

  tasks:
    - name: Create directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ vector_config_dir }}"
        - "{{ vector_data_dir }}"
        - "{{ vector_dir }}"

    - name: Download Vector archive
      ansible.builtin.get_url:
        url: "{{ vector_url }}"
        dest: "/tmp/vector.tar.gz"

    - name: Extract Vector
      become: true
      ansible.builtin.unarchive:
        src: "/tmp/vector.tar.gz"
        dest: "{{ vector_dir }}"
        extra_opts: [--strip-components=2] 
        remote_src: true
        creates: "{{ vector_dir }}/bin/vector"

    - name: Apply Vector template
      become: true
      ansible.builtin.template:
        src: templates/vector.toml.j2
        dest: "{{ vector_config_dir }}/vector.toml"
        mode: '0644'
      notify: Restart Vector