---
- name: Install Git and Nginx
  become: true
  ansible.builtin.yum:
    name:
      - git
      - nginx
    state: present

- name: Enable Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  ignore_errors: true

- name: Clone Lighthouse repo
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    dest: "{{ lighthouse_location_dir }}"
    version: master
    force: true

- name: Apply Nginx config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/lighthouse.conf"
    mode: '0644'
  notify: Restart Nginx