version: '3'
services:
  ubuntu:
    image: pycontribs/ubuntu:latest # Образ с уже установленным python для Ansible
    container_name: ubuntu
    command: sleep infinity # Чтобы контейнер не падал
    
  centos7:
    image: pycontribs/centos:7 # Образ с python
    container_name: centos7
    command: sleep infinity
    
  fedora:
    image: pycontribs/fedora:latest
    container_name: fedora
    command: sleep infinity